#!perl

use 5.012;
use warnings;


=for doc
a a' <<  0
b b' <<  8
c c' <<  16
d d' <<  24

i a'|b'|c'|d'

=cut

sub ai($) 
{
	my $a = shift;
	my @o;

	@o = split /\./, $a;
	
	$o[3] | $o[2] << 8 | $o[1] << 16 | $o[0] <<24; 
}


=for doc

a i >> 24 & 255 
b i >> 16 & 255 
c i >>  8 & 255 
d i &  255 

=cut

sub ia($)
{
	my $i = shift;
	join '.', $i >> 24 & 255, $i >> 16 & 255, $i >> 8 & 255, $i & 255; 
}



=for doc

m  ~ (  ( 2 ** (32 - l) ) -1 );

=cut

sub b($)
{
	my $l = shift;

	~(  ( 2 ** (32 - $l) ) -1 );
}
my $test;

$test = shift;
$, = "\t";

say "a", $test;
say "i", ai $test;
say "a'", ia ai $test; 
say "l", 27;
say "m", b 27;
say "m'", ia b 27;
say "m1", b 24;
say "m1'", ia b 24;

