#!/usr/bin/perl 
#use strict;
#use 5.012;
use warnings;


$o = (grep /-l/, @ARGV  ) ? 6 : 44;
@ARGV = '/proc/net/tcp6';
<>;
while (<>)
{
/.{6}0{20}/ && next; 
$_= (unpack "x${o}A32",$_)[0];
$_ =~ s/(..)(..)(..)(..)/\L$4$3:$2$1:/g;
$_ =~ s!:$!! ;

$a{$_}++

}

map {printf "%4d\t%s\n", @{$_} } sort {$a->[0] <=> $b->[0] } map {[$a{$_},$_] } keys %a;

