#!/usr/bin/perl 
use strict;
use 5.012;
use warnings;

no warnings 'uninitialized';

my $str =  ' /localiplocalportremoteipremoteportstatusuidinodeprocnettcp6';

$, = "\n"; 
$" = "/";

sub u{eval{ unpack$_[0]=~s/([^a-z])/'A'.(ord ($1)-42)/erg,$_[1]} }
sub i{$_[1] =~ s!(..)(..)(..)(..)!$4$3:$2$1:!rg  =~ s!:$!!rg;}


my @s = u '++13240-/.-.' ,$str;
my $p = "</@s[9..11 ]";

my %r;
my $d = shift;

print @s;
print "\n";

print "p=$p";
open p,$p;


while (<p>)
{
	#"A4xxA32xA4xA32xA4xA2xA8xA8xA2xA8xA8xxA11xAxA8x";
	@r{@s[ 3 , 2, 5, 4 ],'rest'} = u ".xxJx.xJx.x,x2x2x,x2x2xx5x+x2x", $_;
 
	
	while (my ($k,$v) = each %r )
	{
		printf "%-24s %s\n", $k, $v;
	}
	say '--';
	
}





if ($d)
{
	printf "%3d\t%s\n",  ($_ - 42, chr $_ )   for  42 .. 126;#0 .. 9, 'A' .. 'Z', 'a' .. 'z';
 
}



__END__
my $pat = "A4xxA32xA4xA32xA4xA2xA8xA8xA2xA8xA8xxA11xAxA8x";


while (<>)
{
#	say "line = ", $_;
	my %r; 
	@r{ 'id', 'localip_raw', 'localport', 'remoteip_raw', 
            'remoteport', 'status', 'txq', 'rxq','timeractive','timerexpire', 
            'rto_timeouts', 'uid', 'u_probes', 'inode'} =

          eval {unpack $pat, $_ };
	warn $@ if $@;
	say "t = ",    $r{localip_raw} =~  s!(..)(..)(..)(..)!$4$3:$2$1:!rg  =~ s!:$!!rg; 
	
	next;

	while (my ($k,$v) = each %r )
	{
		printf "%-24s %s\n", $k, $v;
	}
	say '--';
}


