# Perl version 5						DO NOT EDIT
#
# Generated by smidump 0.4.8:
#
#   smidump -f perl SMCA-MGMT-PG-STATUS-ACTIVITY-MIB

{
"SMCA-MGMT-PG-STATUS-ACTIVITY-MIB" => {
    "name" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",

    #    Compiler Info
    "path" => "pg.stat.activity.mib",
    "language" => "SMIv2",

    #    Module Identity
    "organization" => 
        'smca',
    "contact" =>    
        'email: nobody@sanemail.de',
    "description" =>
        'Postgres Server status - mapping of pg_stat_activity view
one row per server process holding information related to 
the current activity of that process, such as state and current query',
    "revisions" => [
        {
            "date" => "2015-02-23 00:00",
            "description" =>
                'First draft',
        },
    ],
    "identity" => "pg-status-activity",

    #    Imports
    "imports" => [
        {
            "module" => "SNMPv2-SMI",
            "names" => [
                "MODULE-IDENTITY",
                "OBJECT-TYPE",
                "Integer32",
            ]
        },
        {
            "module" => "SNMPv2-CONF",
            "names" => [
                "OBJECT-GROUP",
            ],
        }
    ], # imports

    #    Module Body
    "typedefs" => {
        "BackendPid" => {
            "basetype" => "Integer32",
            "ranges" => (
            {
                "min" => "3",
                "max" => "65535"
            },
            ),
            "range" => {
                "min" => "3",
                "max" => "65535"
            },
        }, # BackendPid
        "Oid" => {
            "basetype" => "Integer32",
        }, # Oid
        "Name" => {
            "basetype" => "OctetString",
        }, # Name
        "RegClass" => {
            "basetype" => "Integer32",
            "parent" => {
                "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
                "name" => "Oid",
            },
        }, # RegClass
        "DatabaseId" => {
            "basetype" => "Integer32",
            "parent" => {
                "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
                "name" => "RegClass",
            },
        }, # DatabaseId
        "DatabaseName" => {
            "basetype" => "OctetString",
            "parent" => {
                "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
                "name" => "Name",
            },
        }, # DatabaseName
        "UserId" => {
            "basetype" => "Integer32",
            "parent" => {
                "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
                "name" => "Oid",
            },
        }, # UserId
        "UserName" => {
            "basetype" => "OctetString",
            "parent" => {
                "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
                "name" => "Name",
            },
        }, # UserName
    }, # typedefs

    "nodes" => [
        {
            "name" => "pg-status-activity",
            "type" => "node",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2",
            "status" => "current",
        }, # pg-status-activity
        {
            "name" => "statusTable",
            "type" => "table",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1",
            "status" => "current",
            "description" =>
                'Status table, contains one entry per backend process',
        }, # statusTable
        {
            "name" => "statusEntry",
            "type" => "row",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1",
            "status" => "current",
            "description" =>
                'Status entry, describes the status of a single backend process',
            "index" => [
                { "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB", "name" => "pid" },
            ], #index
        }, # statusEntry
        {
            "name" => "databaseId",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.1",
            "status" => "current",
            "description" =>
                'id (a postgres oid) of the database this backend is connected to.
this maps to pg_stat_activity/datid',
            "syntax" => {
                "type" => { "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB", "name" => "DatabaseId"},
            },
            "access" => "readonly",
        }, # databaseId
        {
            "name" => "databaseName",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.2",
            "status" => "current",
            "description" =>
                'name of the database this backend is connected to.
this maps to pg_stat_activity/datname',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # databaseName
        {
            "name" => "pid",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.3",
            "status" => "current",
            "description" =>
                'Process id of this backend 
this maps to pg_stat_activity/pid',
            "syntax" => {
                "type" => { "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB", "name" => "BackendPid"},
            },
            "access" => "readonly",
        }, # pid
        {
            "name" => "userId",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.4",
            "status" => "current",
            "description" =>
                'User id (a postgres oid) of the user connected to  this backend 
this maps to pg_stat_activity/usesysid',
            "syntax" => {
                "type" => { "module" => "", "name" => "Integer32"},
            },
            "access" => "readonly",
        }, # userId
        {
            "name" => "userName",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.5",
            "status" => "current",
            "description" =>
                'User name of the user connected to  this backend 
this maps to pg_stat_activity/name',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # userName
        {
            "name" => "applicationName",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.6",
            "status" => "current",
            "description" =>
                'Name of the application connected to  this backend 
this maps to pg_stat_activity/application_name',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # applicationName
        {
            "name" => "clientAddress",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.7",
            "status" => "current",
            "description" =>
                'IP address of the client connected to connected to  this backend 
If this field is null it indicated either that the client is 
connected via a Unix socket on server machine or that this is 
an internal process such as autovacuum.
this maps to pg_stat_activity/client_addr',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # clientAddress
        {
            "name" => "clientHostname",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.8",
            "status" => "current",
            "description" =>
                'Host name of the connected client, as reported by a reverse DNS
lookup of client_addr. This field will only be non-null for 
IP connections, and only when log_hostname is enabled.
this maps to pg_stat_activity/client_hostname',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # clientHostname
        {
            "name" => "clientPort",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.9",
            "status" => "current",
            "description" =>
                'TCP port number that the client is using for communication with
this backend, or -1 if a Unix socket is used
this maps to pg_stat_activity/client_port',
            "syntax" => {
                "type" => { "module" => "", "name" => "Integer32"},
            },
            "access" => "readonly",
        }, # clientPort
        {
            "name" => "backendStart",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.10",
            "status" => "current",
            "description" =>
                'Time when this process was started, i.e., when the client 
connected to the server
this maps to pg_stat_activity/backend_start',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # backendStart
        {
            "name" => "transactionStart",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.11",
            "status" => "current",
            "description" =>
                'Time when this process\' current transaction was started, 
or null if no transaction is active. If the current query
is the first of its transaction, this column is equal to
the query_start column.
this maps to pg_stat_activity/xact_start',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # transactionStart
        {
            "name" => "queryStart",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.12",
            "status" => "current",
            "description" =>
                'Time when the currently active query was started, or if
state is not active, when the last query was started
this maps to pg_stat_activity/query_start',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # queryStart
        {
            "name" => "stateChange",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.13",
            "status" => "current",
            "description" =>
                'Time when the state was last changed
this maps to pg_stat_activity/state_change',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # stateChange
        {
            "name" => "waiting",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.14",
            "status" => "current",
            "description" =>
                'True if this backend is currently waiting on a lock
this maps to pg_stat_activity/waiting',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # waiting
        {
            "name" => "state",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.15",
            "status" => "current",
            "description" =>
                'Current overall state of this backend. Possible values are:
active:  The backend is executing a query.
idle:    The backend is waiting for a new client command.
idle in transaction: 
	The backend is in a transaction, but is not currently
	executing a query.
idle in transaction (aborted):
	This state is similar to idle in transaction, except
	one of the statements in the transaction caused an error.
fastpath function call: 
	The backend is executing a fast-path function.
disabled: 
	This state is reported if track_activities is 
	disabled in this backend.
this maps to pg_stat_activity/state',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # state
        {
            "name" => "query",
            "type" => "column",
            "module" => "SMCA-MGMT-PG-STATUS-ACTIVITY-MIB",
            "oid" => "1.3.6.1.4.1.45204.1.1.2.2.1.2.1.1.16",
            "status" => "current",
            "description" =>
                'Text of this backend\'s most recent query. If state is active
this field shows the currently executing query. In all 
other states, it shows the last query that was executed.
this maps to pg_stat_activity/query',
            "syntax" => {
                "type" => { "module" => "", "name" => "OctetString"},
            },
            "access" => "readonly",
        }, # query
    ], # nodes

  } # SMCA-MGMT-PG-STATUS-ACTIVITY-MIB
};
