SMCA-MGMT-PG-STATUS-ACTIVITY-MIB DEFINITIONS ::= BEGIN

IMPORTS
    MODULE-IDENTITY, OBJECT-TYPE, Integer32 FROM SNMPv2-SMI
    OBJECT-GROUP                  	    FROM SNMPv2-CONF;

pg-status-activity MODULE-IDENTITY
    LAST-UPDATED "201502230000Z"
   
     
    ORGANIZATION "smca"
    CONTACT-INFO "email: nobody@sanemail.de"
    DESCRIPTION	 "Postgres Server status - mapping of pg_stat_activity view
		  one row per server process holding information related to 
		  the current activity of that process, such as state and current query"
    REVISION 	"201502230000Z"
    DESCRIPTION	"First draft"
    ::= { iso(1) org(3) dod(6) internet(1) private(4) enterprises(1) 
	  fourhorsemen(45204) sub(1) smca(1) 
	  management(2) postgres(2) status(1) 2 }


databaseId OBJECT-TYPE
    SYNTAX      Integer32
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "id (a postgres oid) of the database this backend is connected to.
		 this maps to pg_stat_activity/datid"
    ::= { pg-status-activity  1 }

databaseName OBJECT-TYPE
    SYNTAX	OCTET STRING
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "name of the database this backend is connected to.
		 this maps to pg_stat_activity/datname"
    ::= { pg-status-activity  2 }

pid OBJECT-TYPE
    SYNTAX	OCTET STRING
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "Process id of this backend 
		 this maps to pg_stat_activity/pid"
    ::= { pg-status-activity  3 }

userId OBJECT-TYPE
    SYNTAX	Integer32
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "User id (a postgres oid) of the user connected to  this backend 
		 this maps to pg_stat_activity/usesysid"
    ::= { pg-status-activity  4 }

userName OBJECT-TYPE
    SYNTAX	OCTET STRING
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "User name of the user connected to  this backend 
		 this maps to pg_stat_activity/name"
    ::= { pg-status-activity  5 }

applicationName OBJECT-TYPE
    SYNTAX	OCTET STRING
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "Name of the application connected to  this backend 
		 this maps to pg_stat_activity/name"
    ::= { pg-status-activity  6 }

clientAddress OBJECT-TYPE
    SYNTAX	OCTET STRING
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "IP adress of the client connected to connected to  this backend 
		 If this field is null it indicated either that the client is 
		 connected via a Unix socket on server machine or that this is 
		 an internal process such as autovacuum.
		 this maps to pg_stat_activity/name"
    ::= { pg-status-activity  7 }

clientHostname OBJECT-TYPE
    SYNTAX	OCTET STRING
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "Host name of the connected client, as reported by a reverse DNS
		 lookup of client_addr. This field will only be non-null for 
		 IP connections, and only when log_hostname is enabled.
		 this maps to pg_stat_activity/name"
    ::= { pg-status-activity  8 }

clientPort OBJECT-TYPE
    SYNTAX	Integer32
    MAX-ACCESS  read-only
    STATUS	current
    DESCRIPTION "TCP port number that the client is using for communication with
		 this backend, or -1 if a Unix socket is used
		 this maps to pg_stat_activity/name"
    ::= { pg-status-activity  9 }



END
