
SMCA-TEST-ONE-MIB DEFINITIONS ::= BEGIN

--
-- 1.3.6.1.4.1.45204.0.0.2.1
--

IMPORTS
    MODULE-IDENTITY, OBJECT-TYPE, Integer32,
    NOTIFICATION-TYPE                       FROM SNMPv2-SMI
    SnmpAdminString                         FROM SNMP-FRAMEWORK-MIB
    RowStatus, StorageType                  FROM SNMPv2-TC
    InetAddressType, InetAddress            FROM INET-ADDRESS-MIB
;

smcaTestOne MODULE-IDENTITY
    LAST-UPDATED "201502220000Z"
   
     
    ORGANIZATION "smca"
    CONTACT-INFO "email: nobody@sanemail.de"
    DESCRIPTION  "Test MIB"
    REVISION "201502220000Z"
    DESCRIPTION  "First draft"
    ::= { 1 3 6 1 4 1 45204 0 0 2 1 }

--
-- top level structure
--
testOneScalars OBJECT IDENTIFIER ::= { smcaTestOne 1 }
--
-- Example scalars
--
testOneInteger OBJECT-TYPE
    SYNTAX      Integer32
    MAX-ACCESS  read-write
    STATUS      current
    DESCRIPTION
	"This is a simple object which merely houses a writable
	 integer.  It's only purposes is to hold the value of a single
	 integer.  Writing to it will simply change the value for
	 subsequent GET/GETNEXT/GETBULK retrievals.

	 This example object is implemented in the
	 agent/mibgroup/examples/scalar_int.c file."
    DEFVAL { 42 }
    ::= { testOneScalars 1 }
END
